name: Create a branch for issue

on:
  issues:
    types: [opened]

jobs:
  create-new-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create new branch
        run: |
          echo ${{ github.event.issue.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  