name: New Contributor Joined

on:
  member:
    types: [added]
  push:
    branches:
      - "main"

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: New Issue
          token: ${{secrets.GITHUB_TOKEN}}
          body: Some Issue Body
          #assignees: ChenfourAmine



      
      
      

  
  