name: New Contributor Joined

on:
  member:
    types: [added]

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create new issue
        uses: mrdoodles/open-issue@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Clone the main branch in your local repository
          body: |
            Hello ${{ github.event.member.login }}!
            Welcome to our community! We're glad to have you here.
            To get started, please clone the main branch of our repository 
            to your local machine .  
          assignees: ${{ github.event.member.login }}
        

# uses: ManojCSE17/open-issue@v1.0.0
#         with:
#           token: ${{ secrets.MQL_TOKEN}}
#           title: New Issue
#           body: Some Issue Body
#           assignees: |
#             ChenfourAmine
      
      
      

  
  