name: New Contributor Joined

on:
  member:
    types: [added]
  push:
    branches:
      - "main"

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: mrdoodles/open-issue@v1
        with:
          token: ${{ secrets.MQL_TOKEN }}
          title: New Issue
          body: Some Issue Body
          assignees: ChenfourAmine



      
      
      

  
  