name: New Contributor Joined

on:
  member:
    types: [added]
  push:
    branches:
      - "main"

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create new issue
        uses: mrdoodles/open-issue@v1
        with:
          token: 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
          title: Some Issue Title
          body: Some Issue Body
          assignees: ChenfourAmine
        


# uses: ManojCSE17/open-issue@v1.0.0
#         with:
#           token: ${{ secrets.MQL_TOKEN}}
#           title: New Issue
#           body: Some Issue Body
#           assignees: |
#             ChenfourAmine
      
      
      

  
  