name: New Contributor Joined

on:
  member:
    types: [added]
  push:
    branches:
      - "main"

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: dacbd/create-issue-action@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: New Issue
          body: Some body for the issue



      
      
      

  
  