name: New Contributor Joined

on:
  member:
    types: [added]

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create new issue
        uses: mrdoodles/open-issue@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Clone the main branch in your local repository
          body: Hello ${{ env.collaboratorName }}! Welcome to the repository as a collaborator. To get started, clone the main branch of the repository in your local environment. Thank you for joining us!
          assignees: ${{ env.collaboratorName }}
        

# uses: ManojCSE17/open-issue@v1.0.0
#         with:
#           token: ${{ secrets.MQL_TOKEN}}
#           title: New Issue
#           body: Some Issue Body
#           assignees: |
#             ChenfourAmine
      
      
      

  
  