name: New Contributor Joined

on:
  member:
    types: [added]
  push:
    branches:
      - "main"

jobs:
  create-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create new issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.MQL_TOKEN}}
          title: New Issue
          body: Some Issue Body
          assignees: |
            ChenfourAmine



      
      
      

  
  